package com.shopify.storefront.types;

/**
 * Possible error codes that can be returned by `CartUserError`.
 */
public enum CartErrorCode {
  INVALID,

  LESS_THAN,

  INVALID_MERCHANDISE_LINE,

  MISSING_DISCOUNT_CODE,

  MISSING_NOTE,

  NOTE_TOO_LONG,

  INVALID_DELIVERY_GROUP,

  INVALID_DELIVERY_OPTION,

  INVALID_PAYMENT,

  PAYMENT_METHOD_NOT_SUPPORTED,

  INVALID_PAYMENT_EMPTY_CART,

  VALIDATION_CUSTOM,

  INVALID_METAFIELDS,

  MISSING_CUSTOMER_ACCESS_TOKEN,

  INVALID_COMPANY_LOCATION,

  INVALID_INCREMENT,

  MINIMUM_NOT_MET,

  MAXIMUM_EXCEEDED,

  TOO_MANY_DELIVERY_ADDRESSES,

  ONLY_ONE_DELIVERY_ADDRESS_CAN_BE_SELECTED,

  INVALID_DELIVERY_ADDRESS_ID,

  ADDRESS_FIELD_IS_REQUIRED,

  ADDRESS_FIELD_IS_TOO_LONG,

  ADDRESS_FIELD_CONTAINS_EMOJIS,

  ADDRESS_FIELD_CONTAINS_HTML_TAGS,

  ADDRESS_FIELD_CONTAINS_URL,

  ADDRESS_FIELD_DOES_NOT_MATCH_EXPECTED_PATTERN,

  INVALID_ZIP_CODE_FOR_PROVINCE,

  INVALID_ZIP_CODE_FOR_COUNTRY,

  ZIP_CODE_NOT_SUPPORTED,

  PROVINCE_NOT_FOUND,

  UNSPECIFIED_ADDRESS_ERROR,

  PAYMENTS_CREDIT_CARD_BASE_EXPIRED,

  PAYMENTS_CREDIT_CARD_BASE_GATEWAY_NOT_SUPPORTED,

  PAYMENTS_CREDIT_CARD_GENERIC,

  PAYMENTS_CREDIT_CARD_MONTH_INCLUSION,

  PAYMENTS_CREDIT_CARD_NUMBER_INVALID,

  PAYMENTS_CREDIT_CARD_NUMBER_INVALID_FORMAT,

  PAYMENTS_CREDIT_CARD_VERIFICATION_VALUE_BLANK,

  PAYMENTS_CREDIT_CARD_VERIFICATION_VALUE_INVALID_FOR_CARD_TYPE,

  PAYMENTS_CREDIT_CARD_YEAR_EXPIRED,

  PAYMENTS_CREDIT_CARD_YEAR_INVALID_EXPIRY_YEAR
}
