package com.shopify.storefront.types;

/**
 * Possible error codes that can be returned by `CartUserError`.
 */
public enum CartErrorCode {
  ADDRESS_FIELD_CONTAINS_EMOJIS,

  ADDRESS_FIELD_CONTAINS_HTML_TAGS,

  ADDRESS_FIELD_CONTAINS_URL,

  ADDRESS_FIELD_DOES_NOT_MATCH_EXPECTED_PATTERN,

  ADDRESS_FIELD_IS_REQUIRED,

  ADDRESS_FIELD_IS_TOO_LONG,

  INVALID,

  INVALID_COMPANY_LOCATION,

  INVALID_DELIVERY_ADDRESS_ID,

  INVALID_DELIVERY_GROUP,

  INVALID_DELIVERY_OPTION,

  INVALID_INCREMENT,

  INVALID_MERCHANDISE_LINE,

  INVALID_METAFIELDS,

  INVALID_PAYMENT,

  INVALID_PAYMENT_EMPTY_CART,

  INVALID_ZIP_CODE_FOR_COUNTRY,

  INVALID_ZIP_CODE_FOR_PROVINCE,

  LESS_THAN,

  MAXIMUM_EXCEEDED,

  MINIMUM_NOT_MET,

  MISSING_CUSTOMER_ACCESS_TOKEN,

  MISSING_DISCOUNT_CODE,

  MISSING_NOTE,

  NOTE_TOO_LONG,

  ONLY_ONE_DELIVERY_ADDRESS_CAN_BE_SELECTED,

  PAYMENT_METHOD_NOT_SUPPORTED,

  PROVINCE_NOT_FOUND,

  TOO_MANY_DELIVERY_ADDRESSES,

  UNSPECIFIED_ADDRESS_ERROR,

  VALIDATION_CUSTOM,

  ZIP_CODE_NOT_SUPPORTED
}
