package com.shopify.storefront.types;

/**
 * The code for the cart warning.
 */
public enum CartWarningCode {
  MERCHANDISE_NOT_ENOUGH_STOCK,

  MERCHANDISE_OUT_OF_STOCK,

  PAYMENTS_GIFT_CARDS_UNAVAILABLE,

  DUPLICATE_DELIVERY_ADDRESS,

  DISCOUNT_CODE_NOT_HONOURED,

  DISCOUNT_NOT_FOUND,

  DISCOUNT_CURRENTLY_INACTIVE,

  DISCOUNT_USAGE_LIMIT_REACHED,

  DISCOUNT_CUSTOMER_USAGE_LIMIT_REACHED,

  DISCOUNT_CUSTOMER_NOT_ELIGIBLE,

  DISCOUNT_ELIGIBLE_CUSTOMER_MISSING,

  DISCOUNT_QUANTITY_NOT_IN_RANGE,

  DISCOUNT_PURCHASE_NOT_IN_RANGE,

  DISCOUNT_NO_ENTITLED_LINE_ITEMS,

  DISCOUNT_NO_ENTITLED_SHIPPING_LINES,

  DISCOUNT_INCOMPATIBLE_PURCHASE_TYPE
}
