package com.shopify.storefront.types;

/**
 * The code of the error that occurred during a cart completion attempt.
 */
public enum CompletionErrorCode {
  ERROR,

  INVENTORY_RESERVATION_ERROR,

  PAYMENT_AMOUNT_TOO_SMALL,

  PAYMENT_CALL_ISSUER,

  PAYMENT_CARD_DECLINED,

  PAYMENT_ERROR,

  PAYMENT_GATEWAY_NOT_ENABLED_ERROR,

  PAYMENT_INSUFFICIENT_FUNDS,

  PAYMENT_INVALID_BILLING_ADDRESS,

  PAYMENT_INVALID_CREDIT_CARD,

  PAYMENT_INVALID_CURRENCY,

  PAYMENT_INVALID_PAYMENT_METHOD,

  PAYMENT_TRANSIENT_ERROR
}
