package com.shopify.admin.client;

import com.netflix.graphql.dgs.client.codegen.GraphQLQuery;
import com.shopify.admin.types.MoneyInput;
import java.lang.Override;
import java.lang.String;
import java.util.HashSet;
import java.util.Set;

/**
 * Creates a usage charge for an app subscription with usage-based pricing. The
 * charge counts toward the capped amount limit set when creating the subscription.
 *   
 * Usage records track consumption of app features or services on a per-use
 * basis. You provide the charge amount, a description of what you consumed, and
 * the subscription line item ID. The optional [`idempotencyKey`](https://shopify.dev/docs/api/admin-graphql/latest/objects/AppUsageRecord#field-idempotencyKey)
 * parameter prevents duplicate charges if you send the same request multiple times.
 *   
 * If the new charge would cause total usage charges in the current billing
 * interval to exceed the capped amount, then the mutation returns an error.
 *   
 * Learn more about [creating usage-based subscriptions](https://shopify.dev/docs/apps/launch/billing/subscription-billing/create-usage-based-subscriptions).
 */
public class AppUsageRecordCreateGraphQLQuery extends GraphQLQuery {
  public AppUsageRecordCreateGraphQLQuery(String subscriptionLineItemId, MoneyInput price,
      String description, String idempotencyKey, String queryName, Set<String> fieldsSet) {
    super("mutation", queryName);
    if (subscriptionLineItemId != null || fieldsSet.contains("subscriptionLineItemId")) {
        getInput().put("subscriptionLineItemId", subscriptionLineItemId);
    }if (price != null || fieldsSet.contains("price")) {
        getInput().put("price", price);
    }if (description != null || fieldsSet.contains("description")) {
        getInput().put("description", description);
    }if (idempotencyKey != null || fieldsSet.contains("idempotencyKey")) {
        getInput().put("idempotencyKey", idempotencyKey);
    }
  }

  public AppUsageRecordCreateGraphQLQuery() {
    super("mutation");
  }

  @Override
  public String getOperationName() {
    return "appUsageRecordCreate";
  }

  public static Builder newRequest() {
    return new Builder();
  }

  public static class Builder {
    private Set<String> fieldsSet = new HashSet<>();

    private String subscriptionLineItemId;

    private MoneyInput price;

    private String description;

    private String idempotencyKey;

    private String queryName;

    public AppUsageRecordCreateGraphQLQuery build() {
      return new AppUsageRecordCreateGraphQLQuery(subscriptionLineItemId, price, description, idempotencyKey, queryName, fieldsSet);
               
    }

    /**
     * The ID of the app subscription line item to create the usage record under.
     * This app subscription line item must have a usage pricing plan.
     */
    public Builder subscriptionLineItemId(String subscriptionLineItemId) {
      this.subscriptionLineItemId = subscriptionLineItemId;
      this.fieldsSet.add("subscriptionLineItemId");
      return this;
    }

    /**
     * The price of the app usage record.
     */
    public Builder price(MoneyInput price) {
      this.price = price;
      this.fieldsSet.add("price");
      return this;
    }

    /**
     * The description of the app usage record.
     */
    public Builder description(String description) {
      this.description = description;
      this.fieldsSet.add("description");
      return this;
    }

    /**
     * A unique key generated by the client to avoid duplicate charges. Maximum length of 255 characters.
     */
    public Builder idempotencyKey(String idempotencyKey) {
      this.idempotencyKey = idempotencyKey;
      this.fieldsSet.add("idempotencyKey");
      return this;
    }

    public Builder queryName(String queryName) {
      this.queryName = queryName;
      return this;
    }
  }
}
