package com.shopify.types;

/**
 * Possible error codes that can be returned by `MetafieldDefinitionUpdateUserError`.
 */
public enum MetafieldDefinitionUpdateUserErrorCode {
  PRESENT,

  TOO_LONG,

  NOT_FOUND,

  INVALID_INPUT,

  CAPABILITY_REQUIRED_BUT_DISABLED,

  PINNED_LIMIT_REACHED,

  INTERNAL_ERROR,

  UNSUPPORTED_PINNING,

  TYPE_NOT_ALLOWED_FOR_CONDITIONS,

  METAFIELD_DEFINITION_IN_USE,

  OWNER_TYPE_LIMIT_EXCEEDED_FOR_AUTOMATED_COLLECTIONS,

  METAOBJECT_DEFINITION_CHANGED,

  GRANT_LIMIT_EXCEEDED,

  INVALID_INPUT_COMBINATION,

  INVALID_CONSTRAINTS,

  INVALID_CAPABILITY,

  CAPABILITY_CANNOT_BE_DISABLED,

  ADMIN_ACCESS_INPUT_NOT_ALLOWED
}
