package com.shopify.storefront.client;

import com.netflix.graphql.dgs.client.codegen.GraphQLQuery;
import java.lang.Override;
import java.lang.String;
import java.util.HashSet;
import java.util.Set;

/**
 * Resets a customer's password using the reset URL from a password recovery
 * email. The reset URL is generated by the [`customerRecover`](https://shopify.dev/docs/api/storefront/current/mutations/customerRecover) mutation.
 *   
 * On success, returns the updated
 * [`Customer`](https://shopify.dev/docs/api/storefront/current/objects/Customer) and a new [`CustomerAccessToken`](https://shopify.dev/docs/api/storefront/current/objects/CustomerAccessToken)
 * for immediate authentication.
 *   
 * > Caution:
 * > This mutation handles customer credentials. Ensure the new password is
 * transmitted securely and never logged or exposed in client-side code.
 */
public class CustomerResetByUrlGraphQLQuery extends GraphQLQuery {
  public CustomerResetByUrlGraphQLQuery(String resetUrl, String password, String queryName,
      Set<String> fieldsSet) {
    super("mutation", queryName);
    if (resetUrl != null || fieldsSet.contains("resetUrl")) {
        getInput().put("resetUrl", resetUrl);
    }if (password != null || fieldsSet.contains("password")) {
        getInput().put("password", password);
    }
  }

  public CustomerResetByUrlGraphQLQuery() {
    super("mutation");
  }

  @Override
  public String getOperationName() {
    return "customerResetByUrl";
  }

  public static Builder newRequest() {
    return new Builder();
  }

  public static class Builder {
    private Set<String> fieldsSet = new HashSet<>();

    private String resetUrl;

    private String password;

    private String queryName;

    public CustomerResetByUrlGraphQLQuery build() {
      return new CustomerResetByUrlGraphQLQuery(resetUrl, password, queryName, fieldsSet);
               
    }

    /**
     * The customer's reset password url.
     */
    public Builder resetUrl(String resetUrl) {
      this.resetUrl = resetUrl;
      this.fieldsSet.add("resetUrl");
      return this;
    }

    /**
     * New password that will be set as part of the reset password process.
     */
    public Builder password(String password) {
      this.password = password;
      this.fieldsSet.add("password");
      return this;
    }

    public Builder queryName(String queryName) {
      this.queryName = queryName;
      return this;
    }
  }
}
